language: scala
scala:
  - 2.12.8
jdk:
  - oraclejdk8
before_install:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
    scripts/decrypt-keys.sh; fi
  - export PATH=${PATH}:./vendor/bundle
install:
  - rvm use 2.6.5 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 4.0.0
script:
  - sbt ++$TRAVIS_SCALA_VERSION test scripted
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
    scripts/publish-microsite.sh; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "Not in master branch, skipping
    deploy and release"; fi
